config/routes.rb
Flirtatiously::Application.routes.draw do
  resources :users, except: [:index, :show] do



    resources :messages, only: [:new, :create] do
      get 'conversation', on: :collection
    end

    member do
      post "like"
    end
  end

  resource :user_filter, only: [:update]
  resource :session, only: [:new, :create, :destroy]

  resources :profiles, except: [:new]

  resources :messages, only: [:index, :destroy] do
    get 'sent', on: :collection
  end

  resources :questions, only: [:show, :create, :index] do
    post "answer"
    get "edit_answer"
    put "update_answer"
  end



  resources :responses, only: [:create, :update, :edit]
  #resources :likes, only: [:index, :destroy]

  root to: 'profiles#new'
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  category   :string(255)
#  text       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  attr_accessible :category, :text
  validates :text, presence: true

  has_many :answer_choices, dependent: :destroy,
  foreign_key: :question_id

  has_many :responses, dependent: :destroy,
  foreign_key: :question_id

  has_many :acceptable_responses, dependent: :destroy,
  foreign_key: :question_id

  def self.get_responses(user_id)
    return Question.joins("INNER JOIN answer_choices ON questions.id = answer_choices.question_id INNER JOIN responses ON answer_choices.id = responses.answer_choice_id").select("questions.id AS question_id, questions.text AS question_text, answer_choices.id AS answer_id, answer_choices.text AS answer_text").where("responses.user_id = ?", user_id)


    # Question.joins("LEFT OUTER JOIN responses ON responses.question_id = questions.id LEFT OUTER JOIN acceptable_responses ON responses.question_id = acceptable_responses.question_id").select("questions.id AS question_id, questions.text AS question_text, answers.id AS answer_id, answers.text AS answer_text").where("responses.user_id = ?", user_id)
    #


  end

  def self.get_acceptable_responses(user_id)
    return Question.joins("JOIN answer_choices ON questions.id = answer_choices.question_id INNER JOIN acceptable_responses ON acceptable_responses.answer_choice_id = answer_choices.id").select("questions.id AS question_id, acceptable_responses.answer_choice_id AS answer_id, acceptable_responses.importance AS importance").where("acceptable_responses.user_id = ?", user_id)

  end
        #
    # return Question.select("questions.id AS question_id,
    # acceptable_responses.answer_choice_id AS answer_id,
    # acceptable_responses.importance AS
    # importance").includes(:answer_choices, :responses,
    # :acceptable_responses).select("responses.answer_choice_id AS
    # ASDF").where("acceptable_responses.user_id = ?". user_id)
  end

  # 1.9.3-p392 :005 > class Question
 #  1.9.3-p392 :006?>   def my_responses
 #  1.9.3-p392 :007?>     self.responses.each do |response|
 #  1.9.3-p392 :008 >         p response
 #  1.9.3-p392 :009?>       end
 #  1.9.3-p392 :010?>     end
 #  1.9.3-p392 :011?>   end

 # q = Question.includes(:answer_choices, :responses, :acceptable_responses).first
 #
 # q.my_responses

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :require_current_user!


  def index
    unanswered_questions = Question.pluck(:id) - current_user.answered_questions.pluck(:id)

    random_id = unanswered_questions.sample
    @random_question = (random_id.nil?) ? nil : Question.find(random_id)

    @answered_questions = Response.find_by_sql ["
      SELECT questions.text AS question_text, responses.id AS response_id, answer_choices.text AS answer_text, questions.id AS question_id
      FROM questions
      JOIN answer_choices
      ON questions.id = answer_choices.question_id
      JOIN responses
      ON responses.answer_choice_id = answer_choices.id

      WHERE responses.user_id = ?
      ", current_user.id]

  end

  def edit_answer
    question_id = params[:question_id]
    @answer_choices = Question.joins(:answer_choices).select("questions.id AS question_id, questions.text AS question_text, answer_choices.id AS answer_choice_id, answer_choices.text AS answer_choice_text").where("questions.id = ?", question_id)

    @response = current_user.responses.where(:question_id => question_id).first
    @acceptable_responses = current_user.acceptable_responses.where(:question_id => question_id)


  end

  def update_answer
    #put in transaction.
    question_id = params[:question_id]
    responses = current_user.responses.where(question_id: question_id)
    @response = responses.first

    begin
      @response.transaction do


        # if responses.length is 0, raise error. otherwise, take first.


        @response.update_attributes(params[:response])

        prev_acceptables = current_user.acceptable_responses.where(question_id: question_id)

        new_importance = params[:all_acceptable_response][:importance] #will need to do to_i.
        new_acceptable_ans_ids = params[:acceptable_response][:answer_choice_ids].map(&:to_i)

        new_answer_choice_ids_to_add = new_acceptable_ans_ids.select { |ar_id| prev_acceptables.none? {|prev_ar| prev_ar.answer_choice_id == ar_id}} #bang select

        ar_ids_to_delete = prev_acceptables.select{ |ar| new_acceptable_ans_ids.none? {|ans_id| ar.answer_choice_id == ans_id}}.map(&:id) #bang select

        new_answer_choice_ids_to_add.each do |answer_choice_id|
          AcceptableResponse.create({user_id: current_user.id, answer_choice_id: answer_choice_id, importance: new_importance, question_id: question_id})
        end


        AcceptableResponse.destroy_all(:id => ar_ids_to_delete)
        prev_acceptables.delete_if { |ar| ar_ids_to_delete.include?(ar.id)}

        prev_acceptables.each do |ar|
          ar.update_attributes(importance: new_importance)
        end
      end
      redirect_to profiles_url
    rescue ActiveRecord::RecordInvalid => invalid
      flash[:errors] = "Could not update response."
      redirect_to profiles_url
    end

  end

  def show
    @question = Question.find(params[:id])
  end


  def answer
      begin
        ActiveRecord::Base.transaction do

          @response = current_user.responses.new(params[:response]);


          acceptable_response_attrs = params[:acceptable_response].values.each do |attrs|
            attrs[:importance] = params[:all_acceptable_response][:importance]
            attrs[:question_id] = params[:question_id]
          end

          @acceptable_responses = current_user.acceptable_responses.new(params[:acceptable_response].values)

          @response.save
          @acceptable_responses.each do |acceptable_response|
            acceptable_response.save
          end


          raise "invalid" unless @response.valid? && @acceptable_responses.all? { |obj| obj.valid? }
        end
      rescue
        flash[:errors] = "Error answering the question"
        redirect_to profiles_url
      else
        redirect_to questions_url
      end
  end

  def create

  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit_answer.html.erb
<% question_id = @answer_choices.first.question_id %>
<form action="<%= question_update_answer_url(question_id) %>" method="post">
  <input type="hidden" name="_method" value="PUT">

  <%= auth_token_input %>



  <% question_text = @answer_choices.first.question_text %>
<%= question_text %>

<% @answer_choices.each do |answer_choice| %>
<label><input type="radio" name="response[answer_choice_id]" value="<%= answer_choice.answer_choice_id %>"
  <%= "checked" if (answer_choice.answer_choice_id.to_i == @response.answer_choice_id.to_i) %>>
  <%= answer_choice.answer_choice_text %>
</label><br>

<% end %>


<br>
What you prefer on match:
<br>
<% @answer_choices.each_with_index do |answer_choice, index| %>
<input type="checkbox" name="acceptable_response[answer_choice_ids][]" value="<%= answer_choice.answer_choice_id %>" <%= "checked" if @acceptable_responses.any? {|a_r| a_r.answer_choice_id.to_i == answer_choice.answer_choice_id.to_i} %>>

<%= answer_choice.answer_choice_text%></label><br>

<% end %>

<br>
<br>
Importance<br>

<% importance = @acceptable_responses.first.importance %>

<label><input type="radio" name="all_acceptable_response[importance]" value="0" <%= "checked" if importance == 0 %>>Irrelevant</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="1" <%= "checked" if importance == 1 %>>A little important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="10" <%= "checked" if importance == 10 %>>Important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="50" <%= "checked" if importance == 50 %>>Very important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="250" <%= "checked" if importance == 250 %>>Mandatory</label><br>





<input type="submit" value="Edit your response">
</form>

app/views/questions/index.html.erb
<% if @random_question.nil? %>
You've answered all the questions.

<% else %>
<form action="<%= question_answer_url(@random_question) %>" method="post">
<%= auth_token_input %>
<%= @random_question.text %><br>
<% @random_question.answer_choices.each do |answer_choice| %>
<input type="hidden" name="response[question_id]" value="<%= @random_question.id %>">
<label><input type="radio" name="response[answer_choice_id]" id="answer_answer_choice_id" value="<%= answer_choice.id %>"><%= answer_choice.text %></label><br>
<!-- need to add user_id and question_id -->
<% end %>
<br>
What you prefer on match:
<br>
<% @random_question.answer_choices.each_with_index do |answer_choice, index| %>
<input type="checkbox" name="acceptable_response[<%= index %>][answer_choice_id]" value="<%= answer_choice.id %>"><%= answer_choice.text%></label><br>

<% end %>

<br>
How important is this to you?
<br>
<!-- <input type="hidden" name="all_acceptable_response[question_id]" value="<%= @random_question.id %>"> -->
<label><input type="radio" name="all_acceptable_response[importance]" value="0" checked>Irrelevant</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="1">A little important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="10">Important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="50">Very important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="250">Mandatory</label><br>

<input type="Submit" value="Answer question">
</form>

<% end %>



<hr>

<h1> Answered Questions</h1>

<%= "You have not answered any questions." if @answered_questions.length == 0 %>

<% @answered_questions.each do |question| %>
<p>
<%= question.question_text %>
<br>
<%= question.answer_text %>
<%= link_to "Edit response", question_edit_answer_url(question.question_id) %>
</p>
<% end %>

app/views/questions/show.html.erb
<form action="<%= question_answer_url(@question) %>" method="post">
<%= auth_token_input %>
<%= @question.text %><br>
<% @question.answer_choices.each do |answer_choice| %>
<input type="hidden" name="response[question_id]" value="<%= @question.id %>">
<label><input type="radio" name="response[answer_choice_id]" id="answer_answer_choice_id" value="<%= answer_choice.id %>"><%= answer_choice.text %></label><br>
<!-- need to add user_id and question_id -->
<% end %>
<br>
What you prefer on match:
<br>
<% @question.answer_choices.each_with_index do |answer_choice, index| %>
<input type="checkbox" name="acceptable_response[<%= index %>][answer_choice_id]" value="<%= answer_choice.id %>"><%= answer_choice.text%></label><br>

<% end %>

<br>
How important is this to you?
<br>
<!-- <input type="hidden" name="all_acceptable_response[question_id]" value="<%= @question.id %>"> -->
<label><input type="radio" name="all_acceptable_response[importance]" value="0" checked>Irrelevant</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="1">A little important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="10">Important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="50">Very important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="250">Mandatory</label><br>

<input type="Submit" value="Answer question">
</form>

app/views/questions/show_backup.html.erb
<form action="<%= question_answer_url(@question) %>" method="post">
<%= auth_token_input %>
<%= @question.text %><br>
<% @question.answer_choices.each do |answer_choice| %>
<input type="hidden" name="response[question_id]" value="<%= @question.id %>">
<label><input type="radio" name="response[answer_choice_id]" id="answer_answer_choice_id" value="<%= answer_choice.id %>"><%= answer_choice.text %></label><br>
<!-- need to add user_id and question_id --> 
<% end %>
<br>
What you prefer on match:
<br>
<% @question.answer_choices.each_with_index do |answer_choice, index| %>
<input type="checkbox" name="acceptable_response[<%= index %>][answer_choice_id]" value="<%= answer_choice.id %>"><%= answer_choice.text%></label><br>

<% end %>






ANSWER CHOICE: NO			IMPORTANCE		QUESTION ID		USER ID
ANSWER CHOICE: YES    IMPORTANCE		QUESTION ID   USER ID


<br>
How important is this to you?
<br>
<!-- <input type="hidden" name="all_acceptable_response[question_id]" value="<%= @question.id %>"> -->
<label><input type="radio" name="all_acceptable_response[importance]" value="0">Irrelevant</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="1">A little important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="10">Important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="50">Very important</label><br>
<label><input type="radio" name="all_acceptable_response[importance]" value="250">Mandatory</label><br>

<input type="Submit" value="Answer question">
</form>