config/routes.rb
Flirtatiously::Application.routes.draw do
  resources :users, except: [:index, :show] do



    resources :messages, only: [:new, :create] do
      get 'conversation', on: :collection
    end

    member do
      post "like"
    end
  end

  resource :user_filter, only: [:update]
  resource :session, only: [:new, :create, :destroy]

  resources :profiles, except: [:new]

  resources :messages, only: [:index, :destroy] do
    get 'sent', on: :collection
  end

  resources :questions, only: [:show, :create, :index] do
    post "answer"
    get "edit_answer"
    put "update_answer"
  end



  resources :responses, only: [:create, :update, :edit]
  #resources :likes, only: [:index, :destroy]

  root to: 'profiles#new'
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Message < ActiveRecord::Base
  attr_accessible :body
  validates :body, presence: true

  has_many :message_headers, dependent: :destroy,
  foreign_key: :message_id

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_current_user!
  before_filter :require_not_current_users_page!, only: [:conversation, :new, :create]

  def index
    @messages = Message.joins("INNER JOIN message_headers ON messages.id = message_headers.message_id INNER JOIN users ON message_headers.other_id = users.id").select("message_headers.other_id AS recipient_id, users.username AS recipient_username, messages.body AS body, messages.created_at AS sent_date, message_headers.is_sent AS is_sent").where("message_headers.user_id = ?", current_user.id).order("messages.created_at DESC")
    #includes user?
    #if it says its not read, now set it to is_read
    # if its is_sent last, then italics.
    #limit one per user sent, the one that was created last.

    #in "sent", have it from everyone. just 25 each.
    #have link for destroy.

    #draft.

    #display time it was sent.

    #messages.body #messages.oither
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    other_id = params[:user_id]
    user_id = current_user.id

    @message.message_headers
      .new(header_params(user_id, other_id))

    if @message.save
      redirect_to conversation_user_messages_url(params[:user_id])
    else
      flash.now[:errors] = @message.errors.full_messages
      render :new
    end
  end

  def sent
    @sent_messages = Message.joins("INNER JOIN message_headers ON messages.id = message_headers.message_id INNER JOIN users ON message_headers.other_id = users.id").select("message_headers.other_id AS recipient_id, users.username AS recipient_username, messages.body AS body, messages.created_at AS sent_date").where("message_headers.is_sent = true AND message_headers.user_id = ?", current_user.id).order("messages.created_at DESC")
  end

  def conversation
    #whenever u show, u wanna mark IS READ.
    user_id = current_user.id
    other_id = params[:user_id]
    @other_username = User.find(other_id).username

    @messages = MessageHeader.find_by_sql ["
      SELECT message_headers.is_sent, messages.body
      FROM message_headers JOIN messages
      ON message_headers.message_id = messages.id
      WHERE user_id = ? AND other_id = ?
      ", user_id, other_id]



  end

  def destroy

  end

  private

  def header_params(user_id, other_id)
    user_header = {
      user_id: user_id,
      other_id: other_id,
      is_sent: true,
      is_read: true
    }
    other_header = {
      user_id: other_id,
      other_id: user_id,
      is_sent: false,
      is_read: false
    }

    [user_header, other_header]
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<form action="<%= user_messages_url(user_id) %>" method="post">

  <%= auth_token_input %>

  <label>Body
    <textarea name="message[body]"></textarea>
  </label>

  <input type="submit" value="Send message">
</form>

app/views/messages/conversation.html.erb
<h1> Conversation with <%= @other_username %></h1>

<% @messages.each do |message| %>
<% author = message.is_sent? ? current_user.username : @other_username %>

<b><%= author %></b>: <%= message.body %>
<br>

<% end %>

<%= render "form", user_id: params[:user_id] %>

app/views/messages/index.html.erb
<%= "You have not received any messages yet" if @messages.length == 0 %>

<% @messages.each do |message| %>
<p>
<b>Message with <%= message.recipient_username %>: </b><%= message.body %> <%= "(Sent by me)" if message.is_sent == "t" %>
<br>
<%= message.sent_date %><br>

</p>




<% end %>

app/views/messages/new.html.erb
<%= render "form", user_id: params[:user_id] %>

app/views/messages/sent.html.erb
<h1>Sent Messages</h1>
<hr>
<%= @sent_messages.each do |sent_message| %>

<p>
Recipient: <%= link_to sent_message.recipient_username, profile_url(User.find(sent_message.recipient_id).profile.id) %><br>
From: You<br>
Sent: <%= sent_message.sent_date %><br>
Body: <i><%= sent_message.body %></i>
</p>

<% end %>