config/routes.rb
Flirtatiously::Application.routes.draw do
  resources :users, except: [:index, :show] do



    resources :messages, only: [:new, :create] do
      get 'conversation', on: :collection
    end

    member do
      post "like"
    end
  end

  resource :user_filter, only: [:update]
  resource :session, only: [:new, :create, :destroy]

  resources :profiles, except: [:new]

  resources :messages, only: [:index, :destroy] do
    get 'sent', on: :collection
  end

  resources :questions, only: [:show, :create, :index] do
    post "answer"
    get "edit_answer"
    put "update_answer"
  end



  resources :responses, only: [:create, :update, :edit]
  #resources :likes, only: [:index, :destroy]

  root to: 'profiles#new'
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                 :integer          not null, primary key
#  user_id            :integer
#  sex                :string(255)
#  sexual_orientation :string(255)
#  drugs              :string(255)
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  height             :string(255)
#  body_type          :string(255)
#  diet               :string(255)
#  smokes             :string(255)
#  drinks             :string(255)
#  religion           :string(255)
#  sign               :string(255)
#  education          :string(255)
#  job                :string(255)
#  offspring          :string(255)
#  pets               :string(255)
#  likes              :text
#  latitude           :float
#  longitude          :float
#  zip_code           :integer
#  city               :string(255)
#

class Profile < ActiveRecord::Base
  attr_accessible :description, :drugs, :sex, :sexual_orientation, :user_id, :height, :body_type, :diet, :smokes, :drinks, :religion, :sign, :education, :job, :offspring, :pets, :likes, :zip_code, :latitude, :longitude, :city, :birthday, :big_photo

  validates :zip_code, presence: true
  validates :zip_code, numericality: true
  validates :zip_code, length: { is: 5 }
  belongs_to :user, inverse_of: :profile,
  foreign_key: :user_id

  has_attached_file :big_photo
  validates_attachment_content_type :big_photo, :content_type => /\Aimage\/.*\Z/

  geocoded_by :zip_code
  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      obj.city = geo.city
      obj.zip_code = geo.postal_code
    end
  end
  after_validation :geocode, :reverse_geocode

  def self.apply_filters
    current_user = User.find(12)
    filter = current_user.user_filter

    #put those extra filters in for non-default e.g. filter.sex == "Everyone"
    results = Profile.where("id != ?", current_user.profile.id)

    unless filter.sex.nil? || filter.sex == "Everyone"
      results = results.where(:sex => filter.sex)
    end


    unless filter.beg_age.nil? && filter.end_age.nil?
      start_date =
      ((filter.beg_age.nil?) ? 18 : filter.beg_age).years.ago

      end_date =
      ((filter.end_age.nil?) ? 99 : filter.end_age).years.ago

      results = results.where(:birthday => end_date..start_date)
    end

    unless filter.sexual_orientation.nil? || filter.sexual_orientation == "All"
      results = results.where(:sexual_orientation => filter.sexual_orientation)
    end

    #if filter.distance
    unless filter.distance.nil?
      results.reject! do |result|
        current_user.profile.distance_to(result) > filter.distance
      end
    end

    return results
  end

end

app/models/profile_view.rb
# == Schema Information
#
# Table name: profile_views
#
#  id         :integer          not null, primary key
#  viewer_id  :integer
#  viewee_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProfileView < ActiveRecord::Base
  #display last online date. from updated_at

  attr_accessible :viewee_id, :viewer_id



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :require_logged_in!
  before_filter :require_not_current_users_page!, only: [:show]
  layout "browse_profile", only: [:index]
  def new

  end

  def create
    @user = current_user

    @user.build_profile(params[:profile])

    if @user.save
      redirect_to profile_url(@user.profile)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile

    if @profile.update_attributes(params[:profile])
      redirect_to profile_url(params[:id])
    else
      render :json => @profile.errors.full_messages
    end
  end

  def index
    @user_filter = current_user.user_filter
    @profiles = Profile.apply_filters

  end

  def show
    @profile = Profile.find(params[:id])
    other_user_id = @profile.user.id

    @current_user_responses = Question.get_responses(current_user.id)

    @current_user_acceptables = Question.get_acceptable_responses(current_user.id)

    @other_user_responses = Question.get_responses(other_user_id)

    @other_user_acceptables = Question.get_acceptable_responses(other_user_id)

    @match_info = current_user.calculate_percentages(@profile.user)

    # @other_user_acceptable_responses = get_acceptable_responses(@profile.user.id)
#     @responses = get_responses(@profile.user.id)

   # fail

  end

  def destroy

  end

  private

  # def get_acceptable_responses(other_user_id)
  #   User.find(other_user_id).acceptable_responses
  # end
  #
  # def is_unacceptable?(response, acceptable_responses)
  #
  #
  # end
  #
  # def get_responses(other_user_id)
  #
  #   responses = Response.find_by_sql ["
  #
  #     SELECT questions.id AS question_id,
  #     questions.text AS question_text,
  #     other_user_answer_choices.text AS other_user_answer_text,
  #     other_user_answer_choices.id AS other_user_answer_id,
  #     current_user_responses.answer_choice_id AS current_user_answer_id,
  #     current_user_responses.answer_choice_text AS current_user_answer_text
  #
  #     FROM questions
  #     INNER JOIN responses
  #     AS other_user_responses
  #     ON other_user_responses.question_id = questions.id
  #
  #     INNER JOIN answer_choices
  #     AS other_user_answer_choices
  #     ON other_user_responses.answer_choice_id = other_user_answer_choices.id
  #
  #     LEFT OUTER JOIN
  #     (SELECT responses.question_id AS question_id, answer_choices.id AS answer_choice_id, answer_choices.text AS answer_choice_text
  #     FROM responses
  #     JOIN answer_choices
  #     ON responses.answer_choice_id = answer_choices.id
  #     WHERE responses.user_id = ?)
  #     AS current_user_responses ON
  #     other_user_responses.question_id = current_user_responses.question_id
  #     WHERE other_user_responses.user_id = ?", current_user.id, other_user_id]
  #
  #
  #     return parse_responses(responses, other_user_id)
  # end
  #
  # def parse_responses(responses, other_user_id)
  #   results = [];
  #   current_user_acceptable_responses = current_user.acceptable_responses
  #   other_user_acceptable_responses = User.find(other_user_id).acceptable_responses
  #
  #   responses.each do |response|
  #     resultObj = {}
  #     resultObj[:question_id] = response.question_id
  #     resultObj[:question_text] = response.question_text
  #     resultObj[:other_user_answer_text] = response.other_user_answer_text
  #     resultObj[:other_user_answer_id] = response.other_user_answer_id
  #     resultObj[:current_user_answer_text] = response.current_user_answer_text
  #     resultObj[:current_user_answer_id] = response.current_user_answer_id
  #
  #     resultObj[:acceptable_to_current_user] = is_acceptable?(response, "C", current_user_acceptable_responses)
  #     resultObj[:importance_to_current_user] = find_importance(response.question_id, current_user_acceptable_responses)
  #     resultObj[:acceptable_to_other_user] = is_acceptable?(response, "O", other_user_acceptable_responses)
  #     resultObj[:importance_to_other_user] = find_importance(response.question_id, other_user_acceptable_responses)
  #     results.push(resultObj)
  #   end
  #
  #   return results
  #
  # end
  #
  # def find_importance(question_id, acceptable_responses)
  #   return acceptable_responses.find { |ar| ar.question_id == question_id}.importance
  # end
  #
  #
  # def is_acceptable?(response, user_type, acceptable_responses)
  #   acceptable_for_question = acceptable_responses.select { |ar| ar.question_id == response.question_id}
  #   acceptable_answer_choices = acceptable_for_question.collect(&:answer_choice_id)
  #
  #   #WHY THE FUCK DO I NEED TO_I???
  #
  #   if user_type == "C"
  #    # fail if response.question_id == 4
  #     return acceptable_answer_choices.include?(response.other_user_answer_id.to_i)
  #
  #   else #user is O
  #    # fail if response.question_id == 4
  #     return acceptable_answer_choices.include?(response.current_user_answer_id.to_i)
  #   end
  #
  #
  #
  # end

end

app/helpers/profiles_helper.rb
module ProfilesHelper




end

app/views/profiles/edit.html.erb
<h1> Your profile </h1>

<form action="<%= profile_url(@profile.id) %>" enctype="multipart/form-data" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="PUT">

  Username: <b><%= current_user.username %></b><br>

  <label>Zip code
    <input type="text" name="profile[zip_code]" value="<%= @profile.zip_code%>"></label>
    <%= @profile.city %>

    <br>

    Big Photo
    <input type="file" name="profile[big_photo]">
    <br>

    <label>
      Birthday
      <input name="profile[birthday]" type="date" value="<%= @profile.birthday %>"> <%= age(@profile.birthday) %>
    <label><br>

  <label>Height
    <input type="text" name="profile[height]" value="<%= @profile.height %>">
  </label><br>

<%#= profile. %>
<%#= profile. %>


  <label>Body Type
    <select name="profile[body_type]">

      <% ["", "Rather not say", "Thin", "Overweight", "Skinny", "Average", "Fit", "Jacked", "A little extra", "Curvy", "Full-figured", "Used up"].each do |option_val| %>

      <option value="<%= option_val %>" <%= "selected" if @profile.body_type == option_val %>><%= option_val %></option>
      <% end %>

    </select>
  </label><br>

  <label>Diet
    <select name="profile[diet]">

      <% ["", "Anything", "Vegetarian", "Vegan", "Kosher", "Halal", "Paleo"].each do |option_val| %>

      <option value="<%= option_val %>" <%= "selected" if @profile.diet == option_val %>>
        <%= option_val %></option>
      <% end %>

    </select>
  </label><br>

  <label>Religion
    <select name="profile[religion]">

      <% ["", "Atheism", "Christianity", "Judaism", "Catholicism", "Islam", "Hinduism", "Buddhism"].each do |option_val| %>

      <option value="<%= option_val %>" <%= "selected" if @profile.religion == option_val %>>
        <%= option_val %></option>
      <% end %>

    </select>
  </label><br>


  <label>Drugs?
    <select name="profile[drugs]">

      <% ["", "Often", "Sometimes", "Rarely", "Never"].each do |option_val| %>

      <option value="<%= option_val %>" <%= "selected" if @profile.drugs == option_val %>><%= option_val %></option>
      <% end %>

    </select>
  </label><br>



  <label>Description
    <textarea name="profile[description]"></textarea>
  </label><br>

  <label>Likes
    <textarea name="profile[likes]"></textarea>
  </label><br>

  <input type="submit" value="Save Changes">

</form>

app/views/profiles/index.html.erb
<h3> Search </h3>

<form action="<%= user_filter_url %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="put">

  <input type="text" name="user_filter[beg_age]" value="<%= @user_filter.beg_age %>">

  to

  <input type="text" name="user_filter[end_age]" value="<%= @user_filter.end_age %>">

  years old |

  <select name="user_filter[sexual_orientation]">
    <option value="Straight" <%= "selected" if @user_filter.sexual_orientation == "Straight" %>>Straight</option>
    <option value="Gay" <%= "selected" if @user_filter.sexual_orientation == "Gay" %>>Gay</option>
    <option value="Bisexual" <%= "selected" if @user_filter.sexual_orientation == "Bisexual" %>>Bisexual</option>
    <option value="All" <%= "selected" if @user_filter.sexual_orientation == "All" %>>All</option>
  </select>


  <select name="user_filter[sex]" >
  <option value="Everyone" <%= "selected" if @user_filter.sex == "Everyone" %>>Everyone</option>
  <option value="Male" <%= "selected" if @user_filter.sex == "Male" %>>Male</option>
  <option value="Female" <%= "selected" if @user_filter.sex == "Female" %>>Female</option>
  </select> | <input type="text" name="user_filter[distance]" value="<%= @user_filter.distance %>"> miles away


  <input type="submit" value="Refresh">

</form>

<h3> Profiles </h3>

<ul class="profiles-list group">
  <% @profiles.each do |profile| %>
  <li><%= image_tag(profile.big_photo.url) if profile.big_photo.exists? %>


    <div class="profile-content">
  	<%= link_to profile.user.username, profile_url(profile) %><br>
    <%= age(profile.birthday) %> · <%= profile.city %><br>

    <% percentages = current_user.calculate_percentages(profile.user) %>
    <%= print_percentages(percentages) %><br>
  </div>

  </li>

  <li>
    fdsadf</li>

    <li>
      fdsadf</li>

      <li>
        fdsadf</li>

        <li>
          fdsadf</li>

          <li>
            fdsadf</li>

            <li>
              fdsadf</li>

              <li>fdsdfs</li>
  <% end %>
</ul>

app/views/profiles/new.html.erb
<h1> Make New Profile </h1>

<form action="<%= profiles_url %>" method="post">

  Username: <b><%= current_user.username %></b><br>

  <%= auth_token_input %>
  <label>Drugs?
    <select name="profile[drugs]">
      <option value="Often">Often</option>
      <option value="Sometimes">Sometimes</option>
      <option value="Rarely">Rarely</option>
      <option value="Never">Never</option>
    </select>
  </label>


  <label>Description
    <textarea name="profile[description]"></textarea>
  </label>

  <input type="submit" value="Make New Profile">

</form>

app/views/profiles/show.html.erb
<% content_for :right_col do %>

<%= image_tag(@profile.big_photo.url) if @profile.big_photo.exists? %>
<% end %>
Username: <%= @profile.user.username %><br>
<%= age(@profile.birthday) %> years old | <%= @profile.city %>
<br>

<% percentages = current_user.calculate_percentages(@profile.user) %>

<%= print_percentages(percentages) %>

<br>

<% ["sex", "sexual_orientation", "body_type", "smokes", "drinks", "drugs", "religion", "sign", "education", "job", "offspring", "pets", "description", "likes"].each do |descriptor| %>

<%= descriptor.capitalize %>: <%= (@profile[descriptor].nil?) ? "--" : @profile[descriptor] %><br>


<% end %>

<% if current_user.likes?(@profile.user) %>
	<% if @profile.user.likes?(current_user) %>
	<b> You guys both like each other!</b>
	<% else %>
	<b> You've liked this user already. Let's hope they like you back. </b>
	<% end %>
<% else %>
<br>
<%= button_to "Like User", like_user_url(@profile.user_id), method: :post %>

<% end %>

<br>

<%= link_to "Message User", conversation_user_messages_url(@profile.user_id) %>

<br>

<h3>Questions:</h3>

<%= "This person has not answered any questions." if @other_user_responses.length == 0 %>


<% @other_user_responses.each do |other_response| %>
<p>
<%= other_response.question_text %><br>

<% current_user_response = find_response(other_response.question_id, @current_user_responses) %>

<% if current_user_response.nil? %>

Answer question <%= other_response.question_id %> to see their answer.

<% else %>

His/her response: <%= other_response.answer_text%> <b><%= "UNACCEPTABLE" if is_unacceptable?(other_response, @current_user_acceptables) %></b>
Your response: <%= current_user_response.answer_text %><b> <%= "UNACCEPTABLE" if is_unacceptable?(current_user_response, @other_user_acceptables) %></b>

<% end %>

<p>

<% end %>




<br>