config/routes.rb
Flirtatiously::Application.routes.draw do
  resources :users, except: [:index, :show] do



    resources :messages, only: [:new, :create] do
      get 'conversation', on: :collection
    end

    member do
      post "like"
    end
  end

  resource :user_filter, only: [:update]
  resource :session, only: [:new, :create, :destroy]

  resources :profiles, except: [:new]

  resources :messages, only: [:index, :destroy] do
    get 'sent', on: :collection
  end

  resources :questions, only: [:show, :create, :index] do
    post "answer"
    get "edit_answer"
    put "update_answer"
  end



  resources :responses, only: [:create, :update, :edit]
  #resources :likes, only: [:index, :destroy]

  root to: 'profiles#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flirtatiously</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

</p>
  <header class="group">
    <nav class="main-top group">
      <%= image_tag "logo.png" %>
      <% if logged_in? %>
      Glad to see you back, <%= current_user.username %>!

      <%= link_to "Browse", profiles_url %>


      <%= link_to "Your questions", questions_url %>

      <%= link_to "Messages", messages_url %>

      <%= link_to "Edit your profile", edit_profile_url(current_user.profile.id) %>
      <%= button_to "Sign Out", session_url, method: :delete %>

       <% link_to "Your Messages", messages_url %>

      <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
      <% end %>
    </nav>

  </header>
  <content class="group">
    <%= flash[:errors] if flash[:errors] %> <%= flash[:success] if flash[:success] %>

    <div class="left-col-content">
      <%= yield %>
    </div>


    <div class="right-col"><div class="right-col-block">

      <%= yield :right_col %>

    </div></div>

</content>

</body>
</html>

app/views/layouts/browse_profile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flirtatiously</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

</p>
  <header class="group">
    <nav class="main-top group">
      <%= image_tag "logo.png" %>
      <% if logged_in? %>
      Glad to see you back, <%= current_user.username %>!

      <%= link_to "Browse", profiles_url %>


      <%= link_to "Your questions", questions_url %>

      <%= link_to "Messages", messages_url %>

      <%= link_to "Edit your profile", edit_profile_url(current_user.profile.id) %>
      <%= button_to "Sign Out", session_url, method: :delete %>

       <% link_to "Your Messages", messages_url %>

      <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
      <% end %>
    </nav>

  </header>
  <content class="group">
    <%= flash[:errors] if flash[:errors] %> <%= flash[:success] if flash[:success] %>

      <%= yield %>




</content>

</body>
</html>